name: practice_navigation
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.12
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.6
  go_router: ^5.1.1
  google_fonts: ^3.0.1
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'images/logo.png'

flutter_native_splash:
  color: '#e8dedd'
  image: 'images/welkom.png'

flutter:
  uses-material-design: true
  assets:
    - images/
